
services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: tsdb
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TIMESCALE_TELEMETRY=off
    ports:
      - "5432:5432"
    volumes:
      - tsdb-data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana-oss:11.2.0
    container_name: grafana
    restart: unless-stopped
    env_file: .env
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning

volumes:
  tsdb-data:
  grafana-storage: