apiVersion: 1
datasources:
  - name: Timescale (market)
    type: postgres
    access: proxy
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    url: db:5432
    database: ${POSTGRES_DB}
    jsonData:
      sslmode: disable
      postgresVersion: 1200
      timescaledb: true