import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ChartPanel } from "./components/ChartPanel";
import { MarketDetail } from "./components/MarketDetail";
import { MarketTable } from "./components/MarketTable";
import { formatAge, providerThemes, PROVIDERS } from "./shared";
import { useMarketWorkspace } from "./useMarketWorkspace";
export function MarketWorkspacePage() {
    const workspace = useMarketWorkspace();
    const focusedMarket = workspace.selectedMarkets[workspace.focusedProvider];
    return (_jsxs("main", { className: "workspace-shell", children: [_jsxs("header", { className: "top-bar", children: [_jsxs("div", { className: "top-title", children: [_jsx("span", { className: "brand-block", children: "AlphaDB" }), _jsx("span", { className: "brand-subtitle", children: "Markets Web" }), _jsxs("span", { className: "mode-pill", children: ["Unified Mode \u00B7 Focus ", providerThemes[workspace.focusedProvider].label] })] }), _jsxs("div", { className: "top-meta", children: [_jsxs("span", { children: ["markets ", formatAge(workspace.lastMarketRefreshAt)] }), _jsxs("span", { children: ["chart ", formatAge(workspace.providerState[workspace.focusedProvider].lastChartRefreshAt)] })] })] }), _jsx("div", { className: "headline", children: focusedMarket?.question ?? "Prediction-market workspace" }), _jsxs("section", { className: "command-row", children: [_jsx("div", { className: "provider-switches", children: PROVIDERS.map((provider) => (_jsx("button", { type: "button", className: `command-button ${workspace.focusedProvider === provider ? "active" : ""}`, onClick: () => workspace.setFocusedProvider(provider), children: providerThemes[provider].label }, provider))) }), _jsx("div", { className: "view-switches", children: ["trending", "saved", "recent"].map((mode) => (_jsx("button", { type: "button", className: `command-button ${workspace.viewMode === mode ? "active" : ""}`, onClick: () => workspace.setViewMode(mode), children: mode }, mode))) }), _jsxs("label", { className: "search-block", children: [_jsx("span", { children: "Search" }), _jsx("input", { ref: workspace.searchInputRef, value: workspace.query, onChange: (event) => workspace.setQuery(event.target.value), placeholder: "Search both providers" })] }), _jsxs("label", { className: "token-block", children: [_jsx("span", { children: "API Token" }), _jsxs("div", { className: "token-row", children: [_jsx("input", { value: workspace.apiTokenDraft, onChange: (event) => workspace.setApiTokenDraft(event.target.value), placeholder: "Optional bearer token" }), _jsx("button", { type: "button", className: "command-button active", onClick: workspace.applyApiToken, children: "Apply" })] })] })] }), workspace.authStatus?.enabled && !workspace.authStatus.viewer ? (_jsx("section", { className: "status-banner warning-banner", children: "Backend auth is enabled. Market reads still work, but saved and recent state stay local until you provide `ALPHADB_API_TOKEN`." })) : null, workspace.errorMessage ? _jsx("section", { className: "status-banner error-banner", children: workspace.errorMessage }) : null, _jsx("section", { className: "workspace-grid", children: PROVIDERS.map((provider) => {
                    const selectedMarket = workspace.selectedMarkets[provider];
                    const theme = providerThemes[provider];
                    const shellStyle = {
                        "--provider-border": theme.border,
                        "--provider-border-soft": theme.borderSoft,
                        "--provider-panel": theme.panel,
                        "--provider-text": theme.text,
                        "--provider-selected": theme.selected,
                    };
                    return (_jsxs("div", { className: `provider-column ${workspace.focusedProvider === provider ? "focused-column" : ""}`, style: shellStyle, children: [_jsxs("div", { className: "provider-heading", children: [_jsx("span", { children: theme.label }), _jsx("span", { className: "provider-side", children: provider === "polymarket" ? "left" : "right" })] }), _jsx(MarketTable, { provider: provider, markets: workspace.displayedMarkets[provider], selectedIndex: workspace.providerState[provider].selectedIndex, focused: workspace.focusedProvider === provider, savedIds: workspace.savedIds, recentIds: workspace.recentIds, onSelect: (index) => workspace.selectMarket(provider, index) }), _jsx(ChartPanel, { provider: provider, points: workspace.providerState[provider].chartPoints, loading: workspace.providerState[provider].loadingChart }), _jsx(MarketDetail, { provider: provider, market: selectedMarket, liveStatus: workspace.providerState[provider].liveStatusMessage, saved: selectedMarket ? workspace.savedIds.has(selectedMarket.id) : false })] }, provider));
                }) }), _jsxs("footer", { className: "footer-bar", children: [_jsxs("div", { className: "footer-hints", children: [_jsx("span", { children: "1 polymarket" }), _jsx("span", { children: "2 kalshi" }), _jsx("span", { children: "3 reset" }), _jsx("span", { children: "h/l focus" }), _jsx("span", { children: "j/k move" }), _jsx("span", { children: "[ ] range" }), _jsx("span", { children: "f save" }), _jsx("span", { children: "/ search" })] }), _jsx("div", { className: "footer-status", children: workspace.loadingMarkets ? "Loading markets…" : workspace.statusMessage })] })] }));
}
